version: '3'

services:

  virujh-frontend:
    container_name: virujh-frontend
    restart: on-failure
    build:
     context: ./config
     dockerfile: Dockerfile
    ports:
      - "81:80"
    volumes:
      - ./build:/var/www/html/app
      - ./config/nginx/local/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./virujh-static:/var/www/html
    networks:
      - app-network

  php:
    container_name: test-php
    build:
      context: ./config
      dockerfile: Dockerfile-php
    volumes:
      - ./virujh-static:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

    

