FROM nginx
RUN mkdir -p /usr/share/nginx/html/app
RUN mkdir -p /etc/virujh-ca
COPY nginx/development/nginx.conf /etc/nginx/conf.d/default.conf
COPY sshKey/development/. /etc/virujh-ca/.
COPY ./build/. /usr/share/nginx/html/app/
COPY ./virujh-static/. /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]