version: '3'

services:

  virujh-frontend:
    container_name: virujh-nginx
    restart: on-failure
    build:
     context: .
     dockerfile: ./docker-config/Dockerfile
    ports:
      - "81:80"
    volumes:
      - ./docker-config/nginx/local/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  php:
    container_name: php-service
    build:
      context: .
      dockerfile: ./docker-config/Dockerfile-php
    volumes:
      - ./virujh-static:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

    

