FROM nginx
RUN mkdir -p /var/www/html/app
RUN mkdir -p /etc/virujh-ca
COPY ./docker-config/nginx/production/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./docker-config/sshKey/production/. /etc/virujh-ca/.
COPY ./build/. /var/www/html/app/.
COPY ./virujh-static/. /var/www/html/.
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]